
(if (== (load-dynamic-library "libGL") 0)
  (load-dynamic-library "opengl32"))

/* Boolean values */
(define GL_FALSE				0)
(define GL_TRUE					1)

/* Data types */
(define GL_BYTE					0x1400)
(define GL_UNSIGNED_BYTE			0x1401)
(define GL_SHORT				0x1402)
(define GL_UNSIGNED_SHORT			0x1403)
(define GL_INT					0x1404)
(define GL_UNSIGNED_INT				0x1405)
(define GL_FLOAT				0x1406)
(define GL_2_BYTES				0x1407)
(define GL_3_BYTES				0x1408)
(define GL_4_BYTES				0x1409)
(define GL_DOUBLE				0x140A)

/* Primitives */
(define GL_POINTS				0x0000)
(define GL_LINES				0x0001)
(define GL_LINE_LOOP				0x0002)
(define GL_LINE_STRIP				0x0003)
(define GL_TRIANGLES				0x0004)
(define GL_TRIANGLE_STRIP			0x0005)
(define GL_TRIANGLE_FAN				0x0006)
(define GL_QUADS				0x0007)
(define GL_QUAD_STRIP				0x0008)
(define GL_POLYGON				0x0009)

/* Fog */
(define GL_FOG					0x0B60)
(define GL_FOG_MODE				0x0B65)
(define GL_FOG_DENSITY				0x0B62)
(define GL_FOG_COLOR				0x0B66)
(define GL_FOG_INDEX				0x0B61)
(define GL_FOG_START				0x0B63)
(define GL_FOG_END				0x0B64)
(define GL_LINEAR				0x2601)
(define GL_EXP					0x0800)
(define GL_EXP2					0x0801)

(define GL_RGB					0x1907)
(define GL_RGBA					0x1908)

/* Texture mapping */
(define GL_TEXTURE_ENV				0x2300)
(define GL_TEXTURE_ENV_MODE			0x2200)
(define GL_TEXTURE_1D				0x0DE0)
(define GL_TEXTURE_2D				0x0DE1)
(define GL_TEXTURE_WRAP_S			0x2802)
(define GL_TEXTURE_WRAP_T			0x2803)
(define GL_TEXTURE_MAG_FILTER			0x2800)
(define GL_TEXTURE_MIN_FILTER			0x2801)
(define GL_TEXTURE_ENV_COLOR			0x2201)
(define GL_TEXTURE_GEN_S			0x0C60)
(define GL_TEXTURE_GEN_T			0x0C61)
(define GL_TEXTURE_GEN_R			0x0C62)
(define GL_TEXTURE_GEN_Q			0x0C63)
(define GL_TEXTURE_GEN_MODE			0x2500)
(define GL_TEXTURE_BORDER_COLOR			0x1004)
(define GL_TEXTURE_WIDTH			0x1000)
(define GL_TEXTURE_HEIGHT			0x1001)
(define GL_TEXTURE_BORDER			0x1005)
(define GL_TEXTURE_COMPONENTS			0x1003)
(define GL_TEXTURE_RED_SIZE			0x805C)
(define GL_TEXTURE_GREEN_SIZE			0x805D)
(define GL_TEXTURE_BLUE_SIZE			0x805E)
(define GL_TEXTURE_ALPHA_SIZE			0x805F)
(define GL_TEXTURE_LUMINANCE_SIZE		0x8060)
(define GL_TEXTURE_INTENSITY_SIZE		0x8061)
(define GL_NEAREST_MIPMAP_NEAREST		0x2700)
(define GL_NEAREST_MIPMAP_LINEAR		0x2702)
(define GL_LINEAR_MIPMAP_NEAREST		0x2701)
(define GL_LINEAR_MIPMAP_LINEAR			0x2703)
(define GL_OBJECT_LINEAR			0x2401)
(define GL_OBJECT_PLANE				0x2501)
(define GL_EYE_LINEAR				0x2400)
(define GL_EYE_PLANE				0x2502)
(define GL_SPHERE_MAP				0x2402)
(define GL_DECAL				0x2101)
(define GL_MODULATE				0x2100)
(define GL_NEAREST				0x2600)
(define GL_REPEAT				0x2901)
(define GL_CLAMP				0x2900)
(define GL_S					0x2000)
(define GL_T					0x2001)
(define GL_R					0x2002)
(define GL_Q					0x2003)

/* Vertex Arrays */
(define GL_VERTEX_ARRAY				0x8074)
(define GL_NORMAL_ARRAY				0x8075)
(define GL_COLOR_ARRAY				0x8076)
(define GL_INDEX_ARRAY				0x8077)
(define GL_TEXTURE_COORD_ARRAY			0x8078)
(define GL_EDGE_FLAG_ARRAY			0x8079)
(define GL_VERTEX_ARRAY_SIZE			0x807A)
(define GL_VERTEX_ARRAY_TYPE			0x807B)
(define GL_VERTEX_ARRAY_STRIDE			0x807C)
(define GL_NORMAL_ARRAY_TYPE			0x807E)
(define GL_NORMAL_ARRAY_STRIDE			0x807F)
(define GL_COLOR_ARRAY_SIZE			0x8081)
(define GL_COLOR_ARRAY_TYPE			0x8082)
(define GL_COLOR_ARRAY_STRIDE			0x8083)
(define GL_INDEX_ARRAY_TYPE			0x8085)
(define GL_INDEX_ARRAY_STRIDE			0x8086)
(define GL_TEXTURE_COORD_ARRAY_SIZE		0x8088)
(define GL_TEXTURE_COORD_ARRAY_TYPE		0x8089)
(define GL_TEXTURE_COORD_ARRAY_STRIDE		0x808A)
(define GL_EDGE_FLAG_ARRAY_STRIDE		0x808C)
(define GL_VERTEX_ARRAY_POINTER			0x808E)
(define GL_NORMAL_ARRAY_POINTER			0x808F)
(define GL_COLOR_ARRAY_POINTER			0x8090)
(define GL_INDEX_ARRAY_POINTER			0x8091)
(define GL_TEXTURE_COORD_ARRAY_POINTER		0x8092)
(define GL_EDGE_FLAG_ARRAY_POINTER		0x8093)

/* Utility */
(define GL_VENDOR				0x1F00)
(define GL_RENDERER				0x1F01)
(define GL_VERSION				0x1F02)
(define GL_EXTENSIONS				0x1F03)

/* Errors */
(define GL_NO_ERROR 				0)
(define GL_INVALID_ENUM				0x0500)
(define GL_INVALID_VALUE			0x0501)
(define GL_INVALID_OPERATION			0x0502)
(define GL_STACK_OVERFLOW			0x0503)
(define GL_STACK_UNDERFLOW			0x0504)
(define GL_OUT_OF_MEMORY			0x0505)

/* glPush/PopAttrib bits */
(define GL_CURRENT_BIT				0x00000001)
(define GL_POINT_BIT				0x00000002)
(define GL_LINE_BIT				0x00000004)
(define GL_POLYGON_BIT				0x00000008)
(define GL_POLYGON_STIPPLE_BIT			0x00000010)
(define GL_PIXEL_MODE_BIT			0x00000020)
(define GL_LIGHTING_BIT				0x00000040)
(define GL_FOG_BIT				0x00000080)
(define GL_DEPTH_BUFFER_BIT			0x00000100)
(define GL_ACCUM_BUFFER_BIT			0x00000200)
(define GL_STENCIL_BUFFER_BIT			0x00000400)
(define GL_VIEWPORT_BIT				0x00000800)
(define GL_TRANSFORM_BIT			0x00001000)
(define GL_ENABLE_BIT				0x00002000)
(define GL_COLOR_BUFFER_BIT			0x00004000)
(define GL_HINT_BIT				0x00008000)
(define GL_EVAL_BIT				0x00010000)
(define GL_LIST_BIT				0x00020000)
(define GL_TEXTURE_BIT				0x00040000)
(define GL_SCISSOR_BIT				0x00080000)
(define GL_ALL_ATTRIB_BITS			0xFFFFFFFF)

/* Matrix Mode */
(define GL_MATRIX_MODE				0x0BA0)
(define GL_MODELVIEW				0x1700)
(define GL_PROJECTION				0x1701)
(define GL_TEXTURE				0x1702)

/* Blending */
(define GL_BLEND				0x0BE2)
(define GL_BLEND_SRC				0x0BE1)
(define GL_BLEND_DST				0x0BE0)
(define GL_ZERO					0)
(define GL_ONE					1)
(define GL_SRC_COLOR				0x0300)
(define GL_ONE_MINUS_SRC_COLOR			0x0301)
(define GL_SRC_ALPHA				0x0302)
(define GL_ONE_MINUS_SRC_ALPHA			0x0303)
(define GL_DST_ALPHA				0x0304)
(define GL_ONE_MINUS_DST_ALPHA			0x0305)
(define GL_DST_COLOR				0x0306)
(define GL_ONE_MINUS_DST_COLOR			0x0307)
(define GL_SRC_ALPHA_SATURATE			0x0308)


/* Depth buffer */
(define GL_NEVER				0x0200)
(define GL_LESS					0x0201)
(define GL_EQUAL				0x0202)
(define GL_LEQUAL				0x0203)
(define GL_GREATER				0x0204)
(define GL_NOTEQUAL				0x0205)
(define GL_GEQUAL				0x0206)
(define GL_ALWAYS				0x0207)
(define GL_DEPTH_TEST				0x0B71)
(define GL_DEPTH_BITS				0x0D56)
(define GL_DEPTH_CLEAR_VALUE			0x0B73)
(define GL_DEPTH_FUNC				0x0B74)
(define GL_DEPTH_RANGE				0x0B70)
(define GL_DEPTH_WRITEMASK			0x0B72)
(define GL_DEPTH_COMPONENT			0x1902)

/* Polygons */
(define GL_POINT				0x1B00)
(define GL_LINE					0x1B01)
(define GL_FILL					0x1B02)
(define GL_CW					0x0900)
(define GL_CCW					0x0901)
(define GL_FRONT				0x0404)
(define GL_BACK					0x0405)
(define GL_POLYGON_MODE				0x0B40)
(define GL_POLYGON_SMOOTH			0x0B41)
(define GL_POLYGON_STIPPLE			0x0B42)
(define GL_EDGE_FLAG				0x0B43)
(define GL_CULL_FACE				0x0B44)
(define GL_CULL_FACE_MODE			0x0B45)
(define GL_FRONT_FACE				0x0B46)
(define GL_POLYGON_OFFSET_FACTOR		0x8038)
(define GL_POLYGON_OFFSET_UNITS			0x2A00)
(define GL_POLYGON_OFFSET_POINT			0x2A01)
(define GL_POLYGON_OFFSET_LINE			0x2A02)
(define GL_POLYGON_OFFSET_FILL			0x8037)

(define GL_ARRAY_BUFFER                   0x8892)

(define GL_STREAM_DRAW                    0x88E0)
(define GL_STREAM_READ                    0x88E1)
(define GL_STREAM_COPY                    0x88E2)
(define GL_STATIC_DRAW                    0x88E4)
(define GL_STATIC_READ                    0x88E5)
(define GL_STATIC_COPY                    0x88E6)
(define GL_DYNAMIC_DRAW                   0x88E8)
(define GL_DYNAMIC_READ                   0x88E9)
(define GL_DYNAMIC_COPY                   0x88EA)

(define GL_COMPILE_STATUS                 0x8B81)
(define GL_LINK_STATUS                    0x8B82)
(define GL_VALIDATE_STATUS                0x8B83)


(define GL_RGB32UI                        0x8D71)
(define GL_RGBA16UI                       0x8D76)
(define GL_RGB16UI                        0x8D77)
(define GL_RGBA8UI                        0x8D7C)
(define GL_RGB8UI                         0x8D7D)
(define GL_RGBA32I                        0x8D82)
(define GL_RGB32I                         0x8D83)
(define GL_RGBA16I                        0x8D88)
(define GL_RGB16I                         0x8D89)
(define GL_RGBA8I                         0x8D8E)
(define GL_RGB8I                          0x8D8F)
(define GL_RED_INTEGER                    0x8D94)
(define GL_GREEN_INTEGER                  0x8D95)
(define GL_BLUE_INTEGER                   0x8D96)
(define GL_RGB_INTEGER                    0x8D98)
(define GL_RGBA_INTEGER                   0x8D99)
(define GL_BGR_INTEGER                    0x8D9A)
(define GL_BGRA_INTEGER                   0x8D9B)
(define GL_SAMPLER_1D_ARRAY               0x8DC0)
(define GL_SAMPLER_2D_ARRAY               0x8DC1)
(define GL_SAMPLER_1D_ARRAY_SHADOW        0x8DC3)
(define GL_SAMPLER_2D_ARRAY_SHADOW        0x8DC4)
(define GL_SAMPLER_CUBE_SHADOW            0x8DC5)
(define GL_UNSIGNED_INT_VEC2              0x8DC6)
(define GL_UNSIGNED_INT_VEC3              0x8DC7)
(define GL_UNSIGNED_INT_VEC4              0x8DC8)
(define GL_INT_SAMPLER_1D                 0x8DC9)
(define GL_INT_SAMPLER_2D                 0x8DCA)
(define GL_INT_SAMPLER_3D                 0x8DCB)
(define GL_INT_SAMPLER_CUBE               0x8DCC)
(define GL_INT_SAMPLER_1D_ARRAY           0x8DCE)
(define GL_INT_SAMPLER_2D_ARRAY           0x8DCF)
(define GL_UNSIGNED_INT_SAMPLER_1D        0x8DD1)
(define GL_UNSIGNED_INT_SAMPLER_2D        0x8DD2)
(define GL_UNSIGNED_INT_SAMPLER_3D        0x8DD3)
(define GL_UNSIGNED_INT_SAMPLER_CUBE      0x8DD4)
(define GL_UNSIGNED_INT_SAMPLER_1D_ARRAY  0x8DD6)
(define GL_UNSIGNED_INT_SAMPLER_2D_ARRAY  0x8DD7)
(define GL_QUERY_WAIT                     0x8E13)
(define GL_QUERY_NO_WAIT                  0x8E14)
(define GL_QUERY_BY_REGION_WAIT           0x8E15)
(define GL_QUERY_BY_REGION_NO_WAIT        0x8E16)
(define GL_BUFFER_ACCESS_FLAGS            0x911F)
(define GL_BUFFER_MAP_LENGTH              0x9120)
(define GL_BUFFER_MAP_OFFSET              0x9121)
(define GL_DEPTH_COMPONENT32F             0x8CAC)
(define GL_DEPTH32F_STENCIL8              0x8CAD)
(define GL_FLOAT_32_UNSIGNED_INT_24_8_REV 0x8DAD)
(define GL_INVALID_FRAMEBUFFER_OPERATION  0x0506)
(define GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING 0x8210)
(define GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE 0x8211)
(define GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE 0x8212)
(define GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE 0x8213)
(define GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE 0x8214)
(define GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE 0x8215)
(define GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE 0x8216)
(define GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE 0x8217)
(define GL_FRAMEBUFFER_DEFAULT            0x8218)
(define GL_FRAMEBUFFER_UNDEFINED          0x8219)
(define GL_DEPTH_STENCIL_ATTACHMENT       0x821A)
(define GL_MAX_RENDERBUFFER_SIZE          0x84E8)
(define GL_DEPTH_STENCIL                  0x84F9)
(define GL_UNSIGNED_INT_24_8              0x84FA)
(define GL_DEPTH24_STENCIL8               0x88F0)
(define GL_TEXTURE_STENCIL_SIZE           0x88F1)
(define GL_TEXTURE_RED_TYPE               0x8C10)
(define GL_TEXTURE_GREEN_TYPE             0x8C11)
(define GL_TEXTURE_BLUE_TYPE              0x8C12)
(define GL_TEXTURE_ALPHA_TYPE             0x8C13)
(define GL_TEXTURE_DEPTH_TYPE             0x8C16)
(define GL_UNSIGNED_NORMALIZED            0x8C17)
(define GL_FRAMEBUFFER_BINDING            0x8CA6)
(define GL_DRAW_FRAMEBUFFER_BINDING       0x8CA6)
(define GL_RENDERBUFFER_BINDING           0x8CA7)
(define GL_READ_FRAMEBUFFER               0x8CA8)
(define GL_DRAW_FRAMEBUFFER               0x8CA9)
(define GL_READ_FRAMEBUFFER_BINDING       0x8CAA)
(define GL_RENDERBUFFER_SAMPLES           0x8CAB)
(define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE 0x8CD0)
(define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME 0x8CD1)
(define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL 0x8CD2)
(define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE 0x8CD3)
(define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER 0x8CD4)
(define GL_FRAMEBUFFER_COMPLETE           0x8CD5)
(define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT 0x8CD6)
(define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT 0x8CD7)
(define GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER 0x8CDB)
(define GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER 0x8CDC)
(define GL_FRAMEBUFFER_UNSUPPORTED        0x8CDD)
(define GL_MAX_COLOR_ATTACHMENTS          0x8CDF)
(define GL_COLOR_ATTACHMENT0              0x8CE0)
(define GL_COLOR_ATTACHMENT1              0x8CE1)
(define GL_COLOR_ATTACHMENT2              0x8CE2)
(define GL_COLOR_ATTACHMENT3              0x8CE3)
(define GL_COLOR_ATTACHMENT4              0x8CE4)
(define GL_COLOR_ATTACHMENT5              0x8CE5)
(define GL_COLOR_ATTACHMENT6              0x8CE6)
(define GL_COLOR_ATTACHMENT7              0x8CE7)
(define GL_COLOR_ATTACHMENT8              0x8CE8)
(define GL_COLOR_ATTACHMENT9              0x8CE9)
(define GL_COLOR_ATTACHMENT10             0x8CEA)
(define GL_COLOR_ATTACHMENT11             0x8CEB)
(define GL_COLOR_ATTACHMENT12             0x8CEC)
(define GL_COLOR_ATTACHMENT13             0x8CED)
(define GL_COLOR_ATTACHMENT14             0x8CEE)
(define GL_COLOR_ATTACHMENT15             0x8CEF)
(define GL_COLOR_ATTACHMENT16             0x8CF0)
(define GL_COLOR_ATTACHMENT17             0x8CF1)
(define GL_COLOR_ATTACHMENT18             0x8CF2)
(define GL_COLOR_ATTACHMENT19             0x8CF3)
(define GL_COLOR_ATTACHMENT20             0x8CF4)
(define GL_COLOR_ATTACHMENT21             0x8CF5)
(define GL_COLOR_ATTACHMENT22             0x8CF6)
(define GL_COLOR_ATTACHMENT23             0x8CF7)
(define GL_COLOR_ATTACHMENT24             0x8CF8)
(define GL_COLOR_ATTACHMENT25             0x8CF9)
(define GL_COLOR_ATTACHMENT26             0x8CFA)
(define GL_COLOR_ATTACHMENT27             0x8CFB)
(define GL_COLOR_ATTACHMENT28             0x8CFC)
(define GL_COLOR_ATTACHMENT29             0x8CFD)
(define GL_COLOR_ATTACHMENT30             0x8CFE)
(define GL_COLOR_ATTACHMENT31             0x8CFF)
(define GL_DEPTH_ATTACHMENT               0x8D00)
(define GL_STENCIL_ATTACHMENT             0x8D20)
(define GL_FRAMEBUFFER                    0x8D40)
(define GL_RENDERBUFFER                   0x8D41)
(define GL_RENDERBUFFER_WIDTH             0x8D42)
(define GL_RENDERBUFFER_HEIGHT            0x8D43)
(define GL_RENDERBUFFER_INTERNAL_FORMAT   0x8D44)

(define GL_FRONT_LEFT				0x0400)
(define GL_FRONT_RIGHT				0x0401)
(define GL_BACK_LEFT				0x0402)
(define GL_BACK_RIGHT				0x0403)
(define GL_AUX0					0x0409)
(define GL_AUX1					0x040A)
(define GL_AUX2					0x040B)
(define GL_AUX3					0x040C)
(define GL_COLOR_INDEX				0x1900)
(define GL_RED					0x1903)
(define GL_GREEN				0x1904)
(define GL_BLUE					0x1905)
(define GL_ALPHA				0x1906)
(define GL_LUMINANCE				0x1909)
(define GL_LUMINANCE_ALPHA			0x190A)

/*
 * OpenGL 1.3
 */

/* multitexture */
(define GL_TEXTURE0				0x84C0)
(define GL_TEXTURE1				0x84C1)
(define GL_TEXTURE2				0x84C2)
(define GL_TEXTURE3				0x84C3)
(define GL_TEXTURE4				0x84C4)
(define GL_TEXTURE5				0x84C5)
(define GL_TEXTURE6				0x84C6)
(define GL_TEXTURE7				0x84C7)
(define GL_TEXTURE8				0x84C8)
(define GL_TEXTURE9				0x84C9)
(define GL_TEXTURE10				0x84CA)
(define GL_TEXTURE11				0x84CB)
(define GL_TEXTURE12				0x84CC)
(define GL_TEXTURE13				0x84CD)
(define GL_TEXTURE14				0x84CE)
(define GL_TEXTURE15				0x84CF)
(define GL_TEXTURE16				0x84D0)
(define GL_TEXTURE17				0x84D1)
(define GL_TEXTURE18				0x84D2)
(define GL_TEXTURE19				0x84D3)
(define GL_TEXTURE20				0x84D4)
(define GL_TEXTURE21				0x84D5)
(define GL_TEXTURE22				0x84D6)
(define GL_TEXTURE23				0x84D7)
(define GL_TEXTURE24				0x84D8)
(define GL_TEXTURE25				0x84D9)
(define GL_TEXTURE26				0x84DA)
(define GL_TEXTURE27				0x84DB)
(define GL_TEXTURE28				0x84DC)
(define GL_TEXTURE29				0x84DD)
(define GL_TEXTURE30				0x84DE)
(define GL_TEXTURE31				0x84DF)
(define GL_ACTIVE_TEXTURE			0x84E0)
(define GL_CLIENT_ACTIVE_TEXTURE		0x84E1)
(define GL_MAX_TEXTURE_UNITS			0x84E2)
/* texture_cube_map */
(define GL_NORMAL_MAP				0x8511)
(define GL_REFLECTION_MAP			0x8512)
(define GL_TEXTURE_CUBE_MAP			0x8513)
(define GL_TEXTURE_BINDING_CUBE_MAP		0x8514)
(define GL_TEXTURE_CUBE_MAP_POSITIVE_X		0x8515)
(define GL_TEXTURE_CUBE_MAP_NEGATIVE_X		0x8516)
(define GL_TEXTURE_CUBE_MAP_POSITIVE_Y		0x8517)
(define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y		0x8518)
(define GL_TEXTURE_CUBE_MAP_POSITIVE_Z		0x8519)
(define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z		0x851A)
(define GL_PROXY_TEXTURE_CUBE_MAP		0x851B)
(define GL_MAX_CUBE_MAP_TEXTURE_SIZE		0x851C)
/* texture_compression */
(define GL_COMPRESSED_ALPHA			0x84E9)
(define GL_COMPRESSED_LUMINANCE			0x84EA)
(define GL_COMPRESSED_LUMINANCE_ALPHA		0x84EB)
(define GL_COMPRESSED_INTENSITY			0x84EC)
(define GL_COMPRESSED_RGB			0x84ED)
(define GL_COMPRESSED_RGBA			0x84EE)
(define GL_TEXTURE_COMPRESSION_HINT		0x84EF)
(define GL_TEXTURE_COMPRESSED_IMAGE_SIZE	0x86A0)
(define GL_TEXTURE_COMPRESSED			0x86A1)
(define GL_NUM_COMPRESSED_TEXTURE_FORMATS	0x86A2)
(define GL_COMPRESSED_TEXTURE_FORMATS		0x86A3)
/* multisample */
(define GL_MULTISAMPLE				0x809D)
(define GL_SAMPLE_ALPHA_TO_COVERAGE		0x809E)
(define GL_SAMPLE_ALPHA_TO_ONE			0x809F)
(define GL_SAMPLE_COVERAGE			0x80A0)
(define GL_SAMPLE_BUFFERS			0x80A8)
(define GL_SAMPLES				0x80A9)
(define GL_SAMPLE_COVERAGE_VALUE		0x80AA)
(define GL_SAMPLE_COVERAGE_INVERT		0x80AB)
(define GL_MULTISAMPLE_BIT			0x20000000)
/* transpose_matrix */
(define GL_TRANSPOSE_MODELVIEW_MATRIX		0x84E3)
(define GL_TRANSPOSE_PROJECTION_MATRIX		0x84E4)
(define GL_TRANSPOSE_TEXTURE_MATRIX		0x84E5)
(define GL_TRANSPOSE_COLOR_MATRIX		0x84E6)
/* texture_env_combine */
(define GL_COMBINE				0x8570)
(define GL_COMBINE_RGB				0x8571)
(define GL_COMBINE_ALPHA			0x8572)
(define GL_SOURCE0_RGB				0x8580)
(define GL_SOURCE1_RGB				0x8581)
(define GL_SOURCE2_RGB				0x8582)
(define GL_SOURCE0_ALPHA			0x8588)
(define GL_SOURCE1_ALPHA			0x8589)
(define GL_SOURCE2_ALPHA			0x858A)
(define GL_OPERAND0_RGB				0x8590)
(define GL_OPERAND1_RGB				0x8591)
(define GL_OPERAND2_RGB				0x8592)
(define GL_OPERAND0_ALPHA			0x8598)
(define GL_OPERAND1_ALPHA			0x8599)
(define GL_OPERAND2_ALPHA			0x859A)
(define GL_RGB_SCALE				0x8573)
(define GL_ADD_SIGNED				0x8574)
(define GL_INTERPOLATE				0x8575)
(define GL_SUBTRACT				0x84E7)
(define GL_CONSTANT				0x8576)
(define GL_PRIMARY_COLOR			0x8577)
(define GL_PREVIOUS				0x8578)
/* texture_env_dot3 */
(define GL_DOT3_RGB				0x86AE)
(define GL_DOT3_RGBA				0x86AF)
/* texture_border_clamp */
(define GL_CLAMP_TO_BORDER			0x812D)

(define-c glGetError ulong)

(define-c glClearColor void float float float float)
(define-c glOrtho void double double double double double double)
(define-c glVertex3f void float float float)
(define-c glVertex3d void double double double)
(define-c glColor3f void float float float)
(define-c glScaled void double double double)
(define-c glTranslated void double double double)
(define-c glRotated void double double double double)
(define-c glFrustum void double double double double double double)
(define-c glTexCoord2f void float float)
(define-c glTexCoord2d void double double)
(define-c glBlendFunc void ulong ulong)

(define-c glDrawArrays void ulong ulong ulong)

(define-c glGenTextures void ulong ptr)
(define-c glBindTexture void ulong ulong)
(define-c glTexParameteri void ulong ulong ulong)
(define-c glTexImage2D void ulong ulong ulong ulong ulong ulong ulong ulong ptr)


; OpenGL 2.0

(define GL_FRAGMENT_SHADER                0x8B30)
(define GL_VERTEX_SHADER                  0x8B31)

(comment
(define-c glCreateShader ulong ulong)
(define-c glCompileShader void ulong)
(define-c glShaderSource void ulong ulong ulong ulong)

(define-c glCreateProgram ulong)
(define-c glAttachShader void ulong ulong)
(define-c glLinkProgram void ulong)

(define-c glUseProgram void ulong)

(define-c glBindBuffer void ulong ulong)
(define-c glVertexAttribPointer void ulong ulong ulong ulong ulong ulong)
(define-c glEnableVertexAttribArray void ulong)

(define-c glGetUniformLocation ulong ulong ptr)

(define-c glUniform1f void ulong float)
(define-c glUniform2f void ulong float float)
(define-c glUniform3f void ulong float float float)
(define-c glUniform4f void ulong float float float float)

(define-c glUniform1i void ulong ulong)
(define-c glUniform2i void ulong ulong ulong)
(define-c glUniform3i void ulong ulong ulong ulong)
(define-c glUniform4i void ulong ulong ulong ulong ulong)

(define-c glBufferData void ulong ulong ptr ulong)

(define-c glVertexAttrib2f void ulong float float)
(define-c glVertexAttrib3f void ulong float float float)
(define-c glVertexAttrib4f void ulong float float float float)

)

(define-c (glCreateShader) ulong ulong)
(define-c (glCompileShader) void ulong)
(define-c (glShaderSource) void ulong ulong ulong ulong)

(define-c (glCreateProgram) ulong)
(define-c (glAttachShader) void ulong ulong)
(define-c (glLinkProgram) void ulong)

(define-c (glUseProgram) void ulong)

(define-c (glBindVertexArray) void ulong)

(define-c (glBindBuffer) void ulong ulong)
(define-c (glBindFramebuffer) void ulong ulong)
(define-c (glVertexAttribPointer) void ulong ulong ulong ulong ulong ulong)
(define-c (glEnableVertexAttribArray) void ulong)

(define-c (glGetUniformLocation) ulong ulong ptr)

(define-c (glUniform1f) void ulong float)
(define-c (glUniform2f) void ulong float float)
(define-c (glUniform3f) void ulong float float float)
(define-c (glUniform4f) void ulong float float float float)

(define-c (glUniform1i) void ulong ulong)
(define-c (glUniform2i) void ulong ulong ulong)
(define-c (glUniform3i) void ulong ulong ulong ulong)
(define-c (glUniform4i) void ulong ulong ulong ulong ulong)

(define-c (glBufferData) void ulong ulong ptr ulong)

(define-c (glVertexAttrib2f) void ulong float float)
(define-c (glVertexAttrib3f) void ulong float float float)
(define-c (glVertexAttrib4f) void ulong float float float float)

(define-c (glUniformMatrix4fv) void ulong ulong ulong ptr)

(define-c (glGetProgramiv) void ulong ulong ptr)
(define-c (glActiveTexture) void ulong)
(define-c (glGenBuffers) void ulong ptr)
(define-c (glGenVertexArrays) void ulong ptr)
(define-c (glGenFramebuffers) void ulong ptr)

(define-c (glFramebufferTexture2D) void ulong ulong ulong ulong ulong)
(define-c (glGenRenderbuffers) void ulong ptr)
(define-c (glBindRenderbuffer) void ulong ulong)
(define-c (glRenderbufferStorage) void ulong ulong ulong ulong)
(define-c (glFramebufferRenderbuffer) void ulong ulong ulong ulong)

(define-c (glGenerateMipmap) void ulong)

(define (get-gl-function name)
  (let addr (get-function-pointer name))
  (if (== addr 0) (set addr (wglGetProcAddress name)))

  (if (== addr 0)
    (do (print "Function ptr 0 - " name "\n") (debug-break)))

  (print name " = " addr "\n")
  addr)

(define (init-gl-functions)
  (set-function-pointer (quote glCompileShader) (get-gl-function "glCompileShader"))

  (set-function-pointer (quote glCreateShader) (get-gl-function "glCreateShader"))
  (set-function-pointer (quote glCompileShader) (get-gl-function "glCompileShader"))
  (set-function-pointer (quote glShaderSource) (get-gl-function "glShaderSource"))

  (set-function-pointer (quote glCreateProgram) (get-gl-function "glCreateProgram"))
  (set-function-pointer (quote glAttachShader) (get-gl-function "glAttachShader"))
  (set-function-pointer (quote glLinkProgram) (get-gl-function "glLinkProgram"))

  (set-function-pointer (quote glUseProgram) (get-gl-function "glUseProgram"))

  (set-function-pointer (quote glBindVertexArray) (get-gl-function "glBindVertexArray"))

  (set-function-pointer (quote glBindBuffer) (get-gl-function "glBindBuffer"))
  (set-function-pointer (quote glBindFramebuffer) (get-gl-function "glBindFramebuffer"))
  (set-function-pointer (quote glVertexAttribPointer) (get-gl-function "glVertexAttribPointer"))
  (set-function-pointer (quote glEnableVertexAttribArray) (get-gl-function "glEnableVertexAttribArray"))

  (set-function-pointer (quote glGetUniformLocation) (get-gl-function "glGetUniformLocation"))

  (set-function-pointer (quote glUniform1f) (get-gl-function "glUniform1f"))
  (set-function-pointer (quote glUniform2f) (get-gl-function "glUniform2f"))
  (set-function-pointer (quote glUniform3f) (get-gl-function "glUniform3f"))
  (set-function-pointer (quote glUniform4f) (get-gl-function "glUniform4f"))

  (set-function-pointer (quote glUniform1i) (get-gl-function "glUniform1i"))
  (set-function-pointer (quote glUniform2i) (get-gl-function "glUniform2i"))
  (set-function-pointer (quote glUniform3i) (get-gl-function "glUniform3i"))
  (set-function-pointer (quote glUniform4i) (get-gl-function "glUniform4i"))

  (set-function-pointer (quote glBufferData) (get-gl-function "glBufferData"))

  (set-function-pointer (quote glVertexAttrib2f) (get-gl-function "glVertexAttrib2f"))
  (set-function-pointer (quote glVertexAttrib3f) (get-gl-function "glVertexAttrib3f"))
  (set-function-pointer (quote glVertexAttrib4f) (get-gl-function "glVertexAttrib4f"))

  (set-function-pointer (quote glUniformMatrix4fv) (get-gl-function "glUniformMatrix4fv"))

  (set-function-pointer (quote glGetProgramiv) (get-gl-function "glGetProgramiv"))
  (set-function-pointer (quote glActiveTexture) (get-gl-function "glActiveTexture"))
  (set-function-pointer (quote glGenBuffers) (get-gl-function "glGenBuffers"))
  (set-function-pointer (quote glGenVertexArrays) (get-gl-function "glGenVertexArrays"))
  (set-function-pointer (quote glGenFramebuffers) (get-gl-function "glGenFramebuffers"))
  (set-function-pointer (quote glFramebufferTexture2D) (get-gl-function "glFramebufferTexture2D"))
  (set-function-pointer (quote glGenRenderbuffers) (get-gl-function "glGenRenderbuffers"))
  (set-function-pointer (quote glBindRenderbuffer) (get-gl-function "glBindRenderbuffer"))
  (set-function-pointer (quote glRenderbufferStorage) (get-gl-function "glRenderbufferStorage"))
  (set-function-pointer (quote glFramebufferRenderbuffer) (get-gl-function "glFramebufferRenderbuffer"))
  (set-function-pointer (quote glGenerateMipmap) (get-gl-function "glGenerateMipmap"))

  )

